version: '3.2'

services:

  abc-postgres:
    container_name: abc-postgres
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /data/pgdata
    ports:
      - 5434:5432
    volumes:
      - abc-postgres-vol:/data/pgdata

  abc-zookeeper:
    container_name: abc-zookeeper
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181

  abc-kafka:
    container_name: abc-kafka
    image: confluentinc/cp-kafka:latest
    depends_on:
      - abc-zookeeper
    ports:
      - 29092:29092
      - 9092:9092   
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: abc-zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://abc-kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
       - abc-kafka-vol:/bitnami/kafka

  abc-kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: abc-kafka-ui
    ports:
      - 8080:8080
    restart: always
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: abc-kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: abc-zookeeper:2181
    
volumes:
  abc-postgres-vol: 
  abc-kafka-vol: