version: '3.2'

services:

  abc-postgres:
    container_name: abc-postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /data/pgdata
    volumes:
      - abc-postgres:/data/pgdata
    ports:
      - "5432:5432"
    expose:
      - "5432"
    restart: unless-stopped
    networks:
      - abc  

  abc-rabbitmq:
    container_name: abc-rabbitmq
    image: 'rabbitmq:3.11.4-management'
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_DEFAULT_VHOST: vhost
    ports:
      - '5672:5672'
      - '15672:15672'
    expose:
      - "5672"    
    volumes:
      - abc-rabbitmq:/var/lib/rabbitmq/mnesia/
    restart: unless-stopped
    networks:
      - abc

  abc-interface:
    container_name: abc-interface
    build: 
      context: ./interface/
      dockerfile: Dockerfile 
    environment:
      DEBUG: ${DEBUG}
      SECRET_KEY: ${SECRET_KEY}     
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}        
    restart: unless-stopped 
    depends_on: 
      - abc-postgres 
      # - abc-rabbitmq 
    ports:
      - 1234:1234
    networks:
      - abc  

networks:
  abc:
    driver: bridge
  
volumes:
  abc-postgres:
  abc-rabbitmq:
  