# Generated by Django 4.1.3 on 2022-11-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password_recovery_key',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
